### PR TITLE
prepend with "export" for non bash compatibility

### PR DESCRIPTION
**Pull request by chrisgorgo**

### CODE REVIEW

**Comment by vsoch** [comment]
Did you test?

**Comment by chrisgorgo** [comment]
Yes. Why? It doesn't work for you?

**Comment by vsoch** [comment]
No I haven't tested - if you have tested I'm happy to merge, otherwise I wouldn't be able to test until tomorrow - let me know your preference! It seems like a small enough change, and the command looks correct, that I'd be happy to just merge. :)

**Comment by chrisgorgo** [comment]
There is no rush.

**Comment by vsoch** [comment]
ok looks good!

image

**Pull request merged**
